In [1]:
from src.models.level_kv_div import klTrainer, utils, network, datasets
from torch.utils.data import DataLoader
import torch

In [2]:
train_dataset = datasets.get_dataset('../data/processed/sample/train.csv', '../data/processed/sample/train.level.grading')
dev_dataset = datasets.get_dataset('../data/processed/sample/dev.csv', '../data/processed/sample/dev.level.grading')


In [3]:
model = network.SiameseNet(network.EmbeddingNet())
learning_rate = 1e-4
batch_size = 2000
num_epoches = 20

verbose = True
device = 'cuda' if torch.cuda.is_available() else 'cpu'
weight_decay = 1e-6
log_epoch = 3

In [4]:
model.embedding_net.fc[0].weight

Parameter containing:
tensor([[ 0.0419, -0.0528, -0.0260,  ...,  0.0621, -0.0572,  0.0571],
        [-0.0534, -0.0178,  0.0108,  ..., -0.0637, -0.0173, -0.0648],
        [ 0.0606,  0.0195, -0.0127,  ..., -0.0230,  0.0148, -0.0570],
        ...,
        [ 0.0127, -0.0402, -0.0581,  ..., -0.0385,  0.0128, -0.0535],
        [ 0.0417, -0.0204, -0.0002,  ...,  0.0081, -0.0396, -0.0666],
        [ 0.0456, -0.0538,  0.0125,  ..., -0.0093,  0.0540, -0.0212]],
       requires_grad=True)

In [5]:
# optimizer
no_decay = ['bias', 'LayerNorm.weight']
optimizer_grouped_parameters = [
    {'params': [p for n, p in model.named_parameters() if not any(
        nd in n for nd in no_decay) and p.requires_grad], 'weight_decay': weight_decay},
    {'params': [p for n, p in model.named_parameters() if any(
        nd in n for nd in no_decay) and p.requires_grad], 'weight_decay': 0.0}
]

optimizer = torch.optim.AdamW(params=optimizer_grouped_parameters, lr=learning_rate)

train_loader = DataLoader(train_dataset, shuffle=False, batch_size=batch_size, pin_memory=True)
dev_loader = DataLoader(dev_dataset, shuffle=False, batch_size=batch_size, pin_memory=True)
model = model.to(device)

In [6]:
best_avg_val_kl_loss, best_model, model = klTrainer.train_with_eval(train_loader, dev_loader, model, optimizer, num_epoches, log_epoch, verbose, device)

mean of sorted_dis: tensor(467.7703, device='cuda:0', grad_fn=<MeanBackward0>)
the weight Parameter containing:
tensor([[ 0.0419, -0.0528, -0.0260,  ...,  0.0621, -0.0572,  0.0571],
        [-0.0534, -0.0178,  0.0108,  ..., -0.0637, -0.0173, -0.0648],
        [ 0.0606,  0.0195, -0.0127,  ..., -0.0230,  0.0148, -0.0570],
        ...,
        [ 0.0127, -0.0402, -0.0581,  ..., -0.0385,  0.0128, -0.0535],
        [ 0.0417, -0.0204, -0.0002,  ...,  0.0081, -0.0396, -0.0666],
        [ 0.0456, -0.0538,  0.0125,  ..., -0.0093,  0.0540, -0.0212]],
       device='cuda:0', requires_grad=True)
gradients of the weight tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0')
mean of sorted_dis: tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
the w

mean of sorted_dis: tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
the weight Parameter containing:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',
       requires_grad=True)
gradients of the weight tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0')
mean of sorted_dis: tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
the weight Parameter containing:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ...,

In [7]:
best_avg_val_kl_loss

inf