In [1]:
import torch
from src.models.level_kv_div import binaryTrainer, utils, network
from torch.utils.data import DataLoader

from sklearn.metrics import classification_report

import torch

In [2]:
test_dataset = binaryTrainer.LargeSparseDataset('../data/processed/sample/dev.csv', 100, balanced=True, random_neg=True)
# test_dataset = binaryTrainer.get_dataset('../data/processed/sample/train.csv', '../data/processed/sample/train.level.grading')
test_dataloader = DataLoader(test_dataset, shuffle=False, batch_size=1024, pin_memory=True)


666 points, 134532 pairs
mutual neighbors: 51636 one-direction neighbors 15630 not neighbors 67266


In [3]:
# torch.save(test_dataset, '../data/train.largeSparseDataset.pt')

In [4]:
model = torch.load('margin_model.pth.tar')

In [5]:
test_loss, (test_acc, test_pred, test_gold, test_dist) = binaryTrainer.val_one_epoch(test_dataloader, model.to('cuda'), 'cuda')

In [6]:
test_acc

0.8335711949573336

In [7]:
test_dist.shape

torch.Size([134532])

In [8]:
test_dist[test_gold == 0.]

tensor([52.9620, 52.7916, 55.1747,  ..., 36.4492, 37.2184, 36.4315])

In [9]:
test_dist[test_gold == -1.]

tensor([0.0000e+00, 1.1373e-02, 1.3457e-02,  ..., 3.7804e+01, 3.7604e+01,
        3.6302e+01])

In [10]:
test_dist[test_gold == 1]

tensor([55.3470, 43.8632, 45.1060,  ..., 37.4561, 43.3611, 43.9530])

In [11]:
len(test_pred[test_gold == 0.])

15630

In [12]:
len(test_pred)

134532

In [13]:
# test_pred[test_pred == 0.] = 1.
# test_gold[test_gold == 0.] = 1.

# test_gold[test_pred != test_gold]

# len(test_gold[test_pred != test_gold])

# 1 - len(test_gold[test_pred != test_gold]) / len(test_pred)

In [14]:
# for x, y, l in test_dataset:
#     if l == 0:
#         print(((x - y) ** 2).sum())

In [15]:
print(classification_report(test_gold.numpy(), test_pred.numpy()))

              precision    recall  f1-score   support

          -1       1.00      0.87      0.93     51636
           0       0.00      0.00      0.00     15630
           1       0.75      1.00      0.86     67266

    accuracy                           0.83    134532
   macro avg       0.58      0.62      0.60    134532
weighted avg       0.76      0.83      0.79    134532



/home/jiajunb/miniconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [16]:
len(test_pred[test_gold == 0.])

15630